sudo: required
services:
  - docker

before_install:
  - docker build -t abahrii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abahrii/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "docker-react-102"
    env: "Docker-react-102-env"
    bucket_name: "elasticbeanstalk-eu-north-1-368956986465"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key: $aws_secret_key